// <auto-generated />
using System;
using Lender.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lender.Data.Migrations
{
    [DbContext(typeof(LenderContext))]
    partial class LenderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lender.Service.Models.Lender", b =>
                {
                    b.Property<Guid>("LenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathToExcelFile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LenderId");

                    b.ToTable("Lenders");
                });

            modelBuilder.Entity("Lender.Service.Models.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KindOperator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Operand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LenderId");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("Lender.Service.Models.Rule", b =>
                {
                    b.HasOne("Lender.Service.Models.Lender", null)
                        .WithMany("RulesList")
                        .HasForeignKey("LenderId");
                });
#pragma warning restore 612, 618
        }
    }
}
